# Generated by Django 5.0 on 2023-12-25 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Specify the name of the tenant user.', max_length=255, verbose_name='Name of tenant user')),
                ('address', models.TextField(help_text='Specify the address of the tenant user.', verbose_name='Address of tenant user')),
                ('document_proof', models.FileField(help_text='Upload/update a document proof file of tenant user', upload_to='uploads/document-proofs/%Y/%m/%d/', verbose_name='Document proof of tenant user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Profile',
                'verbose_name_plural': 'Tenant Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
