# Generated by Django 5.0 on 2023-12-25 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenantprofile'),
        ('property', '0002_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_end_date', models.DateField()),
                ('monthly_rent_date', models.DateField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenantprofile')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.unit')),
            ],
            options={
                'verbose_name': 'Rental Information',
                'verbose_name_plural': 'Rental Information',
                'ordering': ['-created_at'],
            },
        ),
    ]
