# Generated by Django 5.0 on 2023-12-25 14:03

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_rentalinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Automatically generated slug based on the name.', populate_from='name'),
        ),
        migrations.AddField(
            model_name='rentalinformation',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Automatically generated slug based on the tenant name and unit.', populate_from=['tenant', 'unit']),
        ),
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Automatically generated slug based on the property name and type.', populate_from=['property', 'type']),
        ),
    ]
